spring:
  application:
    name: geo
server:
  port: 9091
eureka: 
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul: 
  routes:
    users:
      path: /solution/**
      serviceId: geo-content
    